### ISSUE TITLE
Questions about this repository

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/febio2#1]
I have some comments/questions about this repo. 

1. Will this be the official GitHub repo for FEBio?
2. In order for FEBio to be open source an [OSI approved license](https://opensource.org/licenses) should be added. I did not see one yet, how will FEBio be licensed in the future (I recommend the [Apache-2.0 license](https://opensource.org/licenses/Apache-2.0))?
3. I noticed the _febiosoftware_ github organization calls this repo `febio2` rather than `febio`. Does this mean each major version (e.g. 2, 3, etc.) will have it's own repo? It would be more convenient to simply use the GitHub release tag feature and have just one repo called `febio`.

**Comment by SteveMaas1978** [comment]
Regarding your questions:

1. Yes, in the future FEBio and all it's related software will be moved to this repo. 
2. We decided on the MIT license. All the source code already contains the license text and in addition you can find info on the license in the file Documentation\Copyright-FEBio.txt. 
3. The current organization is based of our svn organization, which indeed uses a separate repo for each major version of FEBio. In the near future we will be moving all our svn repos to GitHub. At that time, we will add an febio repo that will contain the latest version and remove the febio2 repo. 

I hope that answers your questions. Let us know if you have any other, or if you have any comments or suggestions regarding this.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the clarification.
